### ISSUE TITLE
OSX Yosemite: node src/bot.js run Errors

### ISSUE THREAD

**Issue by Chasen88** [hugs/tapsterbot#27]
So following the README, I was able to flash the arduino and run 'npm install' with success. However, when running 'node src/bot.js I recieve the following error. I am not really sure where to start with debugging. 

mtchasen:software chasen$ node src/bot.js
/Users/chasen/workspace/tapsterbot/software/node_modules/johnny-five/node_modules/firmata/lib/firmata.js:1239
  this.transport.write(new Buffer([START_SYSEX, SAMPLING_INTERVAL, (safeint &
                 ^
TypeError: undefined is not a function
    at Board.setSamplingInterval (/Users/chasen/workspace/tapsterbot/software/node_modules/johnny-five/node_modules/firmata/lib/firmata.js:1239:18)
    at null.<anonymous> (/Users/chasen/workspace/tapsterbot/software/node_modules/johnny-five/node_modules/firmata/lib/firmata.js:545:14)
    at g (events.js:199:16)
    at emit (events.js:104:17)
    at Object.SYSEX_RESPONSE.(anonymous function) (/Users/chasen/workspace/tapsterbot/software/node_modules/johnny-five/node_modules/firmata/lib/firmata.js:176:9)
    at null.<anonymous> (/Users/chasen/workspace/tapsterbot/software/node_modules/johnny-five/node_modules/firmata/lib/firmata.js:481:48)
    at SerialPort.emit (events.js:107:17)
    at Object.module.exports.raw [as parser] (/Users/chasen/workspace/tapsterbot/software/node_modules/johnny-five/node_modules/serialport/parsers.js:8:13)
    at Object.SerialPort.opts.dataCallback (/Users/chasen/workspace/tapsterbot/software/node_modules/johnny-five/node_modules/serialport/serialport.js:181:12)
    at SerialPortFactory.SerialPort._emitData (/Users/chasen/workspace/tapsterbot/software/node_modules/johnny-five/node_modules/serialport/serialport.js:396:20)

**Comment by rwaldron** [comment]
What version of Node are you using?

**Comment by Chasen88** [comment]
Hello Rick,

It looks like I am running V0.12.4

 node -v
v0.12.4

**Comment by rwaldron** [comment]
@Chasen88 Use `nvm` or similar to hop back to a version of node in the 0.10.x series then do `npm rebuild` in the `software/` dir and try re-running

**Comment by rwaldron** [comment]
Did `npm install` fail or produce an npm debug log?

**Comment by Chasen88** [comment]
@rwaldron Ill give rolling the version back a shot. The install appeared to be successfully, I don't seen any log files within the directory.

**Comment by Chasen88** [comment]
@rwaldron So it turns out that if I pull the repo for johnny-five directly and install it from git, the error goes away and I am able to run the code. So I dont know what was wrong originally, but it works now.

**Comment by rwaldron** [comment]
I think there is still an issue, because it should install from npm without issues.

**Comment by rwaldron** [comment]
I think I figured it out, Tapster bot has a very old version of Johnny-Five.

**Comment by Chasen88** [comment]
@rwaldron Sorry for prematurely closing the issue. Glad you were able to figure it out.

**Comment by hugs** [comment]
@rwaldron @Chasen88 Thanks for the fixes. And sorry for the headaches! It had been too long since I had downloaded and installed everything from scratch with all the latest versions. I can also confirm that this fix makes it so Tapster works with the latest io.js, too. (io.js version 2.2.1 as I write this...)
