### ISSUE TITLE
node bot.js unspecified "error" event

### ISSUE THREAD

**Issue by hc89yk** [hugs/tapsterbot#30]
So following the README, I was able to flash the arduino and run 'npm install' with success. However, when running 'node src/bot.js I recieve the following error:

Error: Uncaught, unspecified "error" event. ([object Object])
    at Board.emit (events.js:144:17)
    at Board.log (C:\Users\HCC\Desktop\tapsterbot-master\software\node_modules\j
ohnny-five\lib\board.js:630:8)
    at Board.(anonymous function) [as error](C:UsersHCCDesktoptapsterbot-ma
stersoftwarenode_modulesjohnny-fivelibboard.js:641:14)
    at Board.<anonymous> (C:\Users\HCC\Desktop\tapsterbot-master\software\node_m
odules\johnny-five\lib\board.js:418:14)
    at Timer.listOnTimeout (timers.js:92:15)

I tried evrything what I found on the internet but nothing changed.

What can I do now?

**Comment by rwaldron** [comment]
I think you might be missing most of the error message here, it should've displayed this: 

```
$ node eg/keypad-MPR121_SHIELD.js
1457645312961 Device(s) /dev/cu.usbmodem1421
1457645312971 Connected /dev/cu.usbmodem1421
1457645322977 Device or Firmware Error A timeout occurred while connecting to the Board.

Please check that you've properly flashed the board with the correct firmware.
See: https://github.com/rwaldron/johnny-five/wiki/Getting-Started#trouble-shooting

If connecting to a Leonardo or Leonardo clone, press the 'Reset' button on the board, wait approximately 11 seconds for complete reset, then run your program again.
events.js:146
      throw err;
      ^

Error: Uncaught, unspecified "error" event. ([object Object])
    at Board.emit (events.js:144:17)
    at Board.log (/Users/rwaldron/clonez/johnny-five/lib/board.js:630:8)
    at Board.(anonymous function) [as error] (/Users/rwaldron/clonez/johnny-five/lib/board.js:641:14)
    at Board.<anonymous> (/Users/rwaldron/clonez/johnny-five/lib/board.js:418:14)
    at Timer.listOnTimeout (timers.js:92:15)
```

This is caused by one of several possible things: 
- StandardFirmataPlus isn't actually flashed to the board
- The board is browning out due to some power over-draw
- The board is shorting
- The cable is faulty

**Comment by hc89yk** [comment]
Thanks for the help.

I find the issue source...
I change the arduion uno for another one and it works.
So I get a broken arduino....

**Comment by rwaldron** [comment]
Awesome! Glad you resolved the issue :)
